marker_pattern: data/marker_1.dat
marker_width: 101.0
marker_center_x: 0.0
marker_center_y: 0.0
publish_tf: true
publish_visual_markers: true
reverse_transform: false
threshold: 100
use_history: false

error_threshold: 0.6

rot_x: 0.0
rot_y: 0.0
rot_z: 0.0

marker_offset:
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
